---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config-dev
data:
  # Development overrides
  LOG_LEVEL: "info"
  LOG_DEVELOPMENT: "false"
  LOG_ENCODER: "console"
  METRICS_SECURE: "false"
  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://openobserve.keel.svc:5080/api/default/v1/traces"
  OTEL_AUTH_HEADER: "Basic cm9vdEBleGFtcGxlLmNvbTptUERUY1E0RzhOQnJCaXky"
