apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - clusterrolebinding.yaml
  - leaderelection_role.yaml
  - leaderelection_rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
